# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/terraform-boilerplate

    steps:
      - checkout
      - run:
          name: Inspect format of Terraform files
          command: |
            docker run -v $PWD:/data -w="/data" -i -t hashicorp/terraform:light fmt -diff=true
            git diff --exit-code
      - run:
          name: Test the creation of a terraform plan
          command: |
            docker run -v $PWD:/data -w="/data" -i -t hashicorp/terraform:light plan -var "aws_access_key=$TF_VAR_aws_access_key" -var "aws_secret_key=$TF_VAR_aws_secret_key" -var "aws_key_name=$TF_VAR_aws_key_name"
